################ English language ##################
[nl]
languageName = "Nl"
languageCode = "nl-nl"
contentDir = "content/nederlands"
weight = 1

[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
